[package]
name = "luna"
version = "0.1.0"
edition = "2021"
description = "a light weight interpreted programming language"
[package.metadata.bundle]
name = "Luna"
identifier = "luna"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true

[dependencies]
rand = "0.8.5"
