[package]
name = "luna"
version = "0.4.0"
edition = "2021"
description = "a light weight interpreted programming language"
[package.metadata.bundle]
name = "Luna"
identifier = "luna"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true

[dependencies]
chrono = "0.4.34"
rand = "0.8.5"

[lib]
name = "luna_rs"
path = "src/lib.rs"